# -*- coding: utf-8 -*-
"""Jamu Data Keluhan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A5PTdvdY2v9GFUAcs-nziBZ6ZxUN8cyT

# Import Library
"""

import pandas as pd
import re
import nltk
import joblib

from sklearn.model_selection import train_test_split
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import classification_report, accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

nltk.download('punkt')
nltk.download('stopwords')

"""# Load Data"""

df = pd.read_excel("jamu206.xlsx")

df

"""# Info Dataset"""

print(df.info())

"""# Missing value"""

print(df.isnull().sum())

df = df.dropna(subset=['KHASIAT'])

print("Jumlah data setelah drop:", len(df))
print("Sisa missing KHASIAT:", df['KHASIAT'].isnull().sum())

"""# Preprocessing"""

stop_words = set(stopwords.words('indonesian'))

def preprocess(text):
    text = str(text)

    text = text.lower()

    tokens = text.split()


    tokens = [word for word in tokens if word not in stop_words]
    print(f"Tokens: {tokens}")

    return " ".join(tokens)

df['clean'] = df['KHASIAT'].apply(preprocess)

df[['KHASIAT', 'clean']]

"""## Skenario 1 - Membuat label dari kolom khasiat"""

def labeling(text):
    text = str(text).lower()

    if any(k in text for k in [
        'keputih', 'kewanitaan', 'haid', 'miss v', 'rahim'
    ]):
        return 'kesehatan_wanita'

    elif any(k in text for k in [
        'perut', 'lambung', 'maag', 'diare', 'sembelit', 'pencernaan', 'kembung'
    ]):
        return 'pencernaan'

    elif any(k in text for k in [
        'nafsu makan', 'kurus', 'gemuk', 'berat badan', 'metabolisme'
    ]):
        return 'metabolisme'

    elif any(k in text for k in [
        'pegal', 'linu', 'nyeri', 'sendi', 'asam urat', 'rematik'
    ]):
        return 'nyeri'

    elif any(k in text for k in [
        'flu', 'batuk', 'demam', 'masuk angin', 'daya tahan tubuh'
    ]):
        return 'imunitas'

    elif any(k in text for k in [
        'lelah', 'capek', 'stamina', 'energi', 'vitalitas'
    ]):
        return 'stamina'

    else:
        return 'stamina'

df['label'] = df['KHASIAT'].apply(labeling)

df['label'].value_counts()

"""# Split Data"""

X = df['clean']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

"""# Modelling"""

model = Pipeline([
    ('tfidf', TfidfVectorizer(
        max_features=3000,
        ngram_range=(1,2),
        min_df=2,
        max_df=0.9
    )),
    ('nb', MultinomialNB(alpha=0.5))
])

model.fit(X_train, y_train)

"""## Evaluasi Model"""

y_pred = model.predict(X_test)

print("=== HASIL EVALUASI ===")
print(classification_report(y_test, y_pred))

print("Akurasi:", accuracy_score(y_test, y_pred))

"""## Simpan Model"""

joblib.dump(model, 'model_jamu_nb.pkl')

print("Model berhasil disimpan!")

"""## Prediksi"""

def rekomendasi_jamu(query, top_n=10):
    query_clean = preprocess(query)

    tfidf = model.named_steps['tfidf']
    query_vec = tfidf.transform([query_clean])
    data_vec = tfidf.transform(df['clean'])

    similarity = cosine_similarity(query_vec, data_vec).flatten()

    df['score'] = similarity

    hasil = df.sort_values(by='score', ascending=False)[
        ['NAMA JAMU', 'KHASIAT', 'label', 'score']
    ]

    print("\nKeluhan:", query)
    print("Kategori:", model.predict([query_clean])[0])

    return hasil.head(top_n)

hasil = rekomendasi_jamu("saya sering pegal dan nyeri badan habis ngoding")
print(hasil)

"""## Skenario 2 -> Pake word2vec"""

!pip install gensim

from gensim.models import Word2Vec
import numpy as np

X_train_tokens = X_train.apply(lambda x: x.split())
X_test_tokens  = X_test.apply(lambda x: x.split())

w2v_model = Word2Vec(
    sentences=X_train_tokens,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4
)

def sentence_vector(tokens, model):
    vectors = []

    for word in tokens:
        if word in model.wv:
            vectors.append(model.wv[word])

    if len(vectors) == 0:
        return np.zeros(model.vector_size)

    return np.mean(vectors, axis=0)

X_train_vec = np.array([
    sentence_vector(tokens, w2v_model)
    for tokens in X_train_tokens
])

X_test_vec = np.array([
    sentence_vector(tokens, w2v_model)
    for tokens in X_test_tokens
])

from sklearn.naive_bayes import GaussianNB

model_w2v = GaussianNB()
model_w2v.fit(X_train_vec, y_train)

y_pred = model_w2v.predict(X_test_vec)

print("=== HASIL Word2Vec + NB ===")
print(classification_report(y_test, y_pred))
print("Akurasi:", accuracy_score(y_test, y_pred))

def rekomendasi_jamu_w2v(query, top_n=10):
    query_clean = preprocess(query)
    query_tokens = query_clean.split()

    query_vec = sentence_vector(query_tokens, w2v_model).reshape(1, -1)

    data_tokens = df['clean'].apply(lambda x: x.split())
    data_vec = np.array([
        sentence_vector(tokens, w2v_model)
        for tokens in data_tokens
    ])

    similarity = cosine_similarity(query_vec, data_vec).flatten()

    df['score_w2v'] = similarity

    hasil = df.sort_values(by='score_w2v', ascending=False)[
        ['NAMA JAMU', 'KHASIAT', 'label', 'score_w2v']
    ]

    print("\nKeluhan:", query)

    vec_scaled = scaler.transform(query_vec)
    pred_label = model_w2v.predict(vec_scaled)[0]

    print("Kategori:", pred_label)

    return hasil.head(top_n)

